[package]
name = "kyc-verifier"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "25.3.1", features = ["alloc", "hazmat-crypto"] }

[dev-dependencies]
soroban-sdk = { version = "25.3.1", features = ["alloc", "hazmat-crypto", "testutils"] }
hex = "0.4"
