#!/usr/bin/env node
// Converts snarkjs verification_key.json to Rust constants for Soroban.
// Usage: node circom2soroban.js <verification_key.json> > vk_constants.rs
//
// G1 point encoding: 64 bytes (x || y), each 32-byte big-endian
// G2 point encoding: 128 bytes (x_im || x_re || y_im || y_re), each 32-byte big-endian
// Soroban BN254 uses c1||c0 (imaginary||real) ordering for G2.

const fs = require("fs");

const vkPath = process.argv[2];
if (!vkPath) {
  console.error("Usage: node circom2soroban.js <verification_key.json>");
  process.exit(1);
}

const vk = JSON.parse(fs.readFileSync(vkPath, "utf8"));

function hexByte(n) {
  return n.toString(16).padStart(2, "0");
}

function fieldToBytes32(fieldStr) {
  const n = BigInt(fieldStr);
  const bytes = [];
  for (let i = 0; i < 32; i++) {
    bytes.unshift(Number((n >> BigInt(i * 8)) & 0xffn));
  }
  return bytes;
}

function g1ToBytes(point) {
  // point is [x, y, "1"] from snarkjs
  const xBytes = fieldToBytes32(point[0]);
  const yBytes = fieldToBytes32(point[1]);
  return [...xBytes, ...yBytes];
}

function g2ToBytes(point) {
  // snarkjs G2: [[x_re, x_im], [y_re, y_im], ["1","0"]]
  // Soroban BN254: c1||c0 = imaginary||real for each coordinate
  const x_im = fieldToBytes32(point[0][1]);
  const x_re = fieldToBytes32(point[0][0]);
  const y_im = fieldToBytes32(point[1][1]);
  const y_re = fieldToBytes32(point[1][0]);
  return [...x_im, ...x_re, ...y_im, ...y_re];
}

function bytesToRustArray(bytes, name) {
  const hex = bytes.map((b) => `0x${hexByte(b)}`).join(", ");
  return `pub const ${name}: [u8; ${bytes.length}] = [${hex}];`;
}

const alpha_bytes = g1ToBytes(vk.vk_alpha_1);
const beta_bytes = g2ToBytes(vk.vk_beta_2);
const gamma_bytes = g2ToBytes(vk.vk_gamma_2);
const delta_bytes = g2ToBytes(vk.vk_delta_2);
const ic_bytes = vk.IC.map((pt, i) => ({
  name: `VK_IC_${i}`,
  bytes: g1ToBytes(pt),
}));

let out = `// Auto-generated by circom2soroban.js — do not edit manually.
// Circuit: KycEligibility(20), nPublic: ${vk.nPublic}
// Curve: ${vk.curve}, Protocol: ${vk.protocol}
#![allow(clippy::all)]

pub mod vk {
    ${bytesToRustArray(alpha_bytes, "VK_ALPHA")}
    ${bytesToRustArray(beta_bytes, "VK_BETA")}
    ${bytesToRustArray(gamma_bytes, "VK_GAMMA")}
    ${bytesToRustArray(delta_bytes, "VK_DELTA")}
    pub const VK_IC_LEN: usize = ${ic_bytes.length};
`;

for (const { name, bytes } of ic_bytes) {
  out += `    ${bytesToRustArray(bytes, name)}\n`;
}

out += `}
`;

process.stdout.write(out);
